"""empty message

Revision ID: 23868ae6f3a3
Revises: 56789154b03d
Create Date: 2016-05-29 11:49:12.300000

"""

# revision identifiers, used by Alembic.
revision = '23868ae6f3a3'
down_revision = '56789154b03d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environ', sa.Column('env_description', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('environ', 'env__description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environ', sa.Column('env__description', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('environ', 'env_description')
    ### end Alembic commands ###
