"""empty message

Revision ID: 28816df22d83
Revises: fd7877e31aa0
Create Date: 2016-06-04 10:03:50.305000

"""

# revision identifiers, used by Alembic.
revision = '28816df22d83'
down_revision = 'fd7877e31aa0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Enum('no', 'yes'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    ### end Alembic commands ###
