"""empty message

Revision ID: 689b58ea4cdb
Revises: 033dbdd16291
Create Date: 2016-06-02 01:25:51.956000

"""

# revision identifiers, used by Alembic.
revision = '689b58ea4cdb'
down_revision = '033dbdd16291'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('commit_id', sa.VARCHAR(length=200), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('env_id', sa.INTEGER(), nullable=True),
    sa.Column('server_ip', sa.VARCHAR(length=50), nullable=True),
    sa.Column('link_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ex_link_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.Enum('create', 'review_success', 'review_reject', 'deploy_success', 'deploy_fail'), nullable=True),
    sa.Column('rollback_enable', sa.Enum('yes', 'no'), nullable=True),
    sa.Column('action_id', sa.Enum('deploy', 'rollback'), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_env_id'), 'task', ['env_id'], unique=False)
    op.create_index(op.f('ix_task_project_id'), 'task', ['project_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_project_id'), table_name='task')
    op.drop_index(op.f('ix_task_env_id'), table_name='task')
    op.drop_table('task')
    ### end Alembic commands ###
