"""empty message

Revision ID: 75fe4af92296
Revises: ac8f41f3ad1d
Create Date: 2016-06-03 22:29:23.654000

"""

# revision identifiers, used by Alembic.
revision = '75fe4af92296'
down_revision = 'ac8f41f3ad1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_password', sa.VARCHAR(length=100), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_user_email'), 'user', ['user_email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    ### end Alembic commands ###
