"""empty message

Revision ID: 95b759e6cf22
Revises: 9cd0e16b9a12
Create Date: 2016-05-29 13:07:26.416000

"""

# revision identifiers, used by Alembic.
revision = '95b759e6cf22'
down_revision = '9cd0e16b9a12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environ', sa.Column('env_ip', sa.VARCHAR(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environ', 'env_ip')
    ### end Alembic commands ###
