"""add col env_id

Revision ID: 9cd0e16b9a12
Revises: c43f8480f9e0
Create Date: 2016-05-29 11:57:01.561000

"""

# revision identifiers, used by Alembic.
revision = '9cd0e16b9a12'
down_revision = 'c43f8480f9e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environ', sa.Column('env_id', sa.VARCHAR(length=20), nullable=True))
    op.create_index(op.f('ix_environ_env_id'), 'environ', ['env_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_environ_env_id'), table_name='environ')
    op.drop_column('environ', 'env_id')
    ### end Alembic commands ###
