"""empty message

Revision ID: ac8f41f3ad1d
Revises: 689b58ea4cdb
Create Date: 2016-06-02 01:42:51.639000

"""

# revision identifiers, used by Alembic.
revision = 'ac8f41f3ad1d'
down_revision = '689b58ea4cdb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'server_ip')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('server_ip', mysql.VARCHAR(length=50), nullable=True))
    ### end Alembic commands ###
