"""empty message

Revision ID: b1cacf9a265f
Revises: c6d95a682959
Create Date: 2016-06-04 09:59:53.465000

"""

# revision identifiers, used by Alembic.
revision = 'b1cacf9a265f'
down_revision = 'c6d95a682959'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    op.add_column('user', sa.Column('is_admin', sa.Enum('yes', 'no'), nullable=False))
    op.drop_column('user', 'role_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_admin')
    op.create_table('role',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('role_name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
