"""change env_id type

Revision ID: c43f8480f9e0
Revises: 23868ae6f3a3
Create Date: 2016-05-29 11:55:50.801000

"""

# revision identifiers, used by Alembic.
revision = 'c43f8480f9e0'
down_revision = '23868ae6f3a3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_environ_env_id', table_name='environ')
    op.drop_column('environ', 'env_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environ', sa.Column('env_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_environ_env_id', 'environ', ['env_id'], unique=True)
    ### end Alembic commands ###
